#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ricettario.Shared
{
    
    #line 2 "..\..\RecipeTemplate.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class RecipeTemplate : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 3 "..\..\RecipeTemplate.cshtml"
 public Ricettario.Shared.Model.Recipe Recipe { get; set; } 
        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n\r\nName:\r\n");


            
            #line 6 "..\..\RecipeTemplate.cshtml"
 if (!String.IsNullOrWhiteSpace(Recipe.Name))
{
    
            
            #line default
            #line hidden
            
            #line 8 "..\..\RecipeTemplate.cshtml"
Write("\t" + Recipe.Name + Environment.NewLine);

            
            #line default
            #line hidden
            
            #line 8 "..\..\RecipeTemplate.cshtml"
                                               
}

            
            #line default
            #line hidden
WriteLiteral("\r\nYield:\r\n");


            
            #line 12 "..\..\RecipeTemplate.cshtml"
 if (!String.IsNullOrWhiteSpace(Recipe.RecipeYield))
{
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\RecipeTemplate.cshtml"
Write("\t" + Recipe.RecipeYield + Environment.NewLine);

            
            #line default
            #line hidden
            
            #line 14 "..\..\RecipeTemplate.cshtml"
                                                      
}

            
            #line default
            #line hidden
WriteLiteral("\r\nIngredients:\r\n");


            
            #line 18 "..\..\RecipeTemplate.cshtml"
 if (Recipe.RecipeIngredients != null)
{
    foreach (var item in Recipe.RecipeIngredients)
    {
        
            
            #line default
            #line hidden
            
            #line 22 "..\..\RecipeTemplate.cshtml"
    Write("\t" + item + Environment.NewLine);

            
            #line default
            #line hidden
            
            #line 22 "..\..\RecipeTemplate.cshtml"
                                            
    }
}

            
            #line default
            #line hidden
WriteLiteral("\r\nDirections:\r\n");


            
            #line 27 "..\..\RecipeTemplate.cshtml"
 if (Recipe.RecipeInstructions != null)
{
    foreach (var item in Recipe.RecipeInstructions)
    {
        
            
            #line default
            #line hidden
            
            #line 31 "..\..\RecipeTemplate.cshtml"
    Write("\t" + item + Environment.NewLine);

            
            #line default
            #line hidden
            
            #line 31 "..\..\RecipeTemplate.cshtml"
                                            
    }
}

            
            #line default
            #line hidden
WriteLiteral("\r\nDescription:\r\n");


            
            #line 36 "..\..\RecipeTemplate.cshtml"
 if (!String.IsNullOrWhiteSpace(Recipe.RecipeDescription))
{
    
            
            #line default
            #line hidden
            
            #line 38 "..\..\RecipeTemplate.cshtml"
Write("\t" + Recipe.RecipeDescription + Environment.NewLine);

            
            #line default
            #line hidden
            
            #line 38 "..\..\RecipeTemplate.cshtml"
                                                            
}

            
            #line default
            #line hidden
WriteLiteral("\r\nAuthor:\r\n");


            
            #line 42 "..\..\RecipeTemplate.cshtml"
 if (!String.IsNullOrWhiteSpace(Recipe.Author))
{
    
            
            #line default
            #line hidden
            
            #line 44 "..\..\RecipeTemplate.cshtml"
Write("\t" + Recipe.Author + Environment.NewLine);

            
            #line default
            #line hidden
            
            #line 44 "..\..\RecipeTemplate.cshtml"
                                                 
}

            
            #line default
            #line hidden
WriteLiteral("\r\nTags:\r\n");


            
            #line 48 "..\..\RecipeTemplate.cshtml"
 if (Recipe.Tags != null)
{
    foreach (var item in Recipe.Tags)
    {
        
            
            #line default
            #line hidden
            
            #line 52 "..\..\RecipeTemplate.cshtml"
    Write("\t" + item + Environment.NewLine);

            
            #line default
            #line hidden
            
            #line 52 "..\..\RecipeTemplate.cshtml"
                                            
    }
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
